version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_REPO=https://github.com/Iznobadd/BowlingProject.git
    ports:
      - 8080:80
    restart: always
    network_mode: host
